fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app:
    resource: "@AppBundle/Resources/config/routing.yml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
