root:
  path: /
  defaults: {_controller: AppBundle:Serials:index}

serial_view_path:
  path: /serials/{slug}/view
  defaults: {_controller: AppBundle:Serials:show}

season_view_path:
  path: /seasons/{id}/view
  defaults: {_controller: AppBundle:Seasons:show}

episode_view_path:
  path: /episodes/{id}/view
  defaults: {_controller: AppBundle:Episodes:show}

people_view_path:
  path: /peoples/{slug}/view
  defaults: {_controller: AppBundle:Peoples:show}

people_list_path:
  path: /peoples/
  defaults: {_controller: AppBundle:Peoples:index}

genre_view_path:
  path: /genres/{slug}/view
  defaults: {_controller: AppBundle:Genres:show}

genre_list_path:
  path: /genres/
  defaults: {_controller: AppBundle:Genres:index}
